using REA_OOP;

// See https://aka.ms/new-console-template for more information
Console.WriteLine("PRz-11 Bazhin Dmitrii");

Money a1 = new Money();
Money a2 = new Money(123, 206);
Money a3 = new Money(123, 123);
Money a4 = new Money(11);
Money a5 = new Money(0, 2);
Console.WriteLine("Object count: " + Money.Counter);
Console.WriteLine("a2 = " + a2.ToString());
a2 = a2 + (-10);
Console.WriteLine("a2 = " + a2.ToString());
a2++;
a2++;
a2++;
a2++;
Console.WriteLine("a2 = " + a2.ToString());
a2 = a2 + 10;
Console.WriteLine("a2 = " + a2.ToString());
Console.WriteLine("a1 = " + a1.ToString());
a1.Rubles = 1001;
a1.Kopeks = 111;
Console.WriteLine("a1 = " + a1.ToString());
Console.WriteLine("a3 = " + a3.ToString());
Console.WriteLine("a4 = " + a4.ToString());
a4--;
Console.WriteLine("a4 = " + a4.ToString());
a4++;
Console.WriteLine("a4 = " + a4.ToString());
Console.WriteLine("a5 = " + a5.ToString());
a5--;   
Console.WriteLine("a5 = " + a5.ToString());
a5--;
Console.WriteLine("a5 = " + a5.ToString());
a5--;
Console.WriteLine("a5 = " + a5.ToString());
a5--;
Console.WriteLine("a5 = " + a5.ToString());
a1.Rubles = 95;
a1.Kopeks = 95;
a2.Rubles = 10;
a2.Rubles = 10;
Console.WriteLine("a1 = " + a1.ToString());
Console.WriteLine("a2 = " + a2.ToString());
Money a6 = a1 + a2;
Console.WriteLine("a6 = " + a6.ToString());
Money a7 = a1 - a2;
Console.WriteLine("a7 = " + a7.ToString());
Console.WriteLine((int)a1);
Console.WriteLine((double)a1);